# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "126fa8870e14a8abb6a2975ba88c4b87"
application_url = "https://example.com"
embedded = true
name = "Big Collection Filters"

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes"

[auth]
redirect_urls = [ "https://example.com/auth/callback" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
